[instrument_info]
manufacturer='FEI'
model='DB'

[pinout]
ext-ibeam-scan-enable = 0
ext-ibeam-scan-enable-2 = 1
ext-ibeam-blank-enable = 2
ext-ibeam-blank-enable-2 = 3
ibeam-blank-low = 4
ibeam-blank-high = 5
ebeam-blank = 6
ebeam-blank-2 = 7
ext-ebeam-scan-enable = 8
ext-ebeam-scan-enable-2 = 9

[transforms]
xflip = true
rotate90 = true
