[instrument_info]
manufacturer='FEI'
model='DB'

[pinout]
ext-ibeam-scan-enable = 0
ext-ibeam-scan-enable-2 = 1
ext-ibeam-blank-enable = 2
ext-ibeam-blank-enable-2 = 3
ibeam-blank-low = 4
ibeam-blank-high = 5
