name: Export KiCad
on: 
    push:
        paths:
        - '**.sch'
        - '**.kicad_pcb'
        - '.github/workflows/kicad.yml' # Trigger on changes to the workflow file
        - '**.kibot.yml' # Trigger on changes to the KiBot config file used in the workflow
jobs:
  obi:
    runs-on: ubuntu-latest
    env:
        OBI_PATH = '"Hardware/PCBs/Open Beam Interface/Open Beam Interface"'
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.3.1
      with:
      # Required - kibot config file
        config: kibot/kibot.yaml
      # optional - prefix to output defined in config
        dir: kicad_export
      # optional - schematic file
        schema: ${OBI_PATH}.sch
      # optional - PCB design file
        board: ${OBI_PATH}.kicad_pcb
      # optional - verbose output info
        verbose: 0
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: obi_export
        path: ${OBI_PATH}/export
        
