name: Run Unit Tests
  
on: [push]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.12"]  
  
    steps:  
      - name: Check out source code
        uses: actions/checkout@v3  
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Generate lockfile
        working-directory: ./software
        run: pdm lock --group :all ${{ matrix.dep-versions == 'minimal' && '--strategy direct_minimal_versions' || '' }}
      - name: Install dependencies
        working-directory: ./Gateware
        run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
      - name: Run tests  
        run: |  
          pdm run test
        
